# Generated by Django 6.0.4 on 2026-05-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Detailed markdown or HTML content')),
                ('featured', models.BooleanField(default=False)),
                ('live_link', models.URLField(blank=True, max_length=255, null=True)),
                ('repo_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
